src_files = main.c ft_write_999.c ft_spell_number.c helper_functions.c \
	parse_dict.c str_numeric_length.c ft_writing_checks.c
default:
	cc -Wall -Wextra -Werror $(src_files) -o rush-02

fclean:
	rm -f rush-02
